import {
	AirVent,
	Bed,
	Coffee,
	CookingPot,
	Droplets,
	Dumbbell,
	Flame,
	Heater,
	LayoutGrid,
	Microwave,
	Mountain,
	Music,
	PawPrint,
	Pickaxe,
	Refrigerator,
	Siren,
	SoapDispenserDroplet,
	SquareParking,
	TowelRack,
	TreePalm,
	UtensilsCrossed,
	Waves,
	WavesLadder,
	Wifi,
	type LucideIcon,
} from 'lucide-react';

export const Amenities = {
	WIFI: 'wifi',
	POOL: 'pool',
	PARKING: 'parking',
	AC: 'ac',
	KITCHEN: 'kitchen',
	WORKSPACE: 'workspace',
	HEATING: 'heating',
	AIR_CONDITIONING: 'air_conditioning',
	TOWELS: 'towels',
	BED_SHEETS: 'bed_sheets',
	SOAP: 'soap',
	TOILET_PAPER: 'toilet_paper',
	HOT_WATER: 'hot_water',
	HANGERS: 'hangers',
	STOVE: 'stove',
	OVEN: 'oven',
	REFRIGERATOR: 'refrigerator',
	MICROWAVE: 'microwave',
	COFFEE_MAKER: 'coffee_maker',
	KETTLE: 'kettle',
	COOKING_BASICS: 'cooking_basics',
	DISHES_AND_CUTLERY: 'dishes_and_cutlery',
	DISHWASHER: 'dishwasher',
	WASHER: 'washer',
	DRYER: 'dryer',
	IRON: 'iron',
	IRONING_BOARD: 'ironing_board',
	EXTRA_PILLOWS: 'extra_pillows',
	BLANKETS: 'blankets',
	BLACKOUT_CURTAINS: 'blackout_curtains',
	HAIR_DRYER: 'hair_dryer',
	SHAMPOO: 'shampoo',
	CONDITIONER: 'conditioner',
	BODY_SOAP: 'body_soap',
	BATHTUB: 'bathtub',
	SHOWER: 'shower',
	TV: 'tv',
	STREAMING_SERVICES: 'streaming_services',
	SOUND_SYSTEM: 'sound_system',
	BOOKS: 'books',
	BOARD_GAMES: 'board_games',
	FREE_PARKING: 'free_parking',
	PAID_PARKING: 'paid_parking',
	ELEVATOR: 'elevator',
	HOT_TUB: 'hot_tub',
	GYM: 'gym',
	BALCONY: 'balcony',
	PATIO: 'patio',
	GARDEN: 'garden',
	BACKYARD: 'backyard',
	BBQ_GRILL: 'bbq_grill',
	OUTDOOR_FURNITURE: 'outdoor_furniture',
	CRIB: 'crib',
	HIGH_CHAIR: 'high_chair',
	BABY_BATH: 'baby_bath',
	CHILDREN_TOYS: 'children_toys',
	PETS_ALLOWED: 'pets_allowed',
	PET_BED: 'pet_bed',
	PET_BOWLS: 'pet_bowls',
	SMOKE_ALARM: 'smoke_alarm',
	CARBON_MONOXIDE_ALARM: 'carbon_monoxide_alarm',
	FIRST_AID_KIT: 'first_aid_kit',
	FIRE_EXTINGUISHER: 'fire_extinguisher',
	DEDICATED_WORKSPACE: 'dedicated_workspace',
	DESK: 'desk',
	CHAIR: 'chair',
	SEA_VIEW: 'sea_view',
	MOUNTAIN_VIEW: 'mountain_view',
	FIREPLACE: 'fireplace',
	JACUZZI: 'jacuzzi',
	SMART_LOCK: 'smart_lock',
	SMART_HOME_FEATURES: 'smart_home_features',
	OUTDOOR_DINING_AREA: 'outdoor_dining_area',
	FIRE_PIT: 'fire_pit',
	POOL_TABLE: 'pool_table',
	INDOOR_FIREPLACE: 'indoor_fireplace',
	PIANO: 'piano',
	EXERCISE_EQUIPMENT: 'exercise_equipment',
	LAKE_ACCESS: 'lake_access',
	BEACH_ACCESS: 'beach_access',
	SKI_IN_SKI_OUT: 'ski_in_ski_out',
	OUTDOOR_SHOWER: 'outdoor_shower',
} as const;

export type AmenityId = (typeof Amenities)[keyof typeof Amenities];
export type AmenityOption = { label: string; value: AmenityId; icon: LucideIcon };

const amenitiesBaseOptions: Array<{ label: string; value: AmenityId }> = [
	{ label: 'Wi-Fi', value: Amenities.WIFI },
	{ label: 'Pool', value: Amenities.POOL },
	{ label: 'Free parking', value: Amenities.PARKING },
	{ label: 'Air conditioning', value: Amenities.AC },
	{ label: 'Kitchen', value: Amenities.KITCHEN },
	{ label: 'Dedicated workspace', value: Amenities.WORKSPACE },
	{ label: 'Heating', value: Amenities.HEATING },
	{ label: 'Air conditioning (full)', value: Amenities.AIR_CONDITIONING },
	{ label: 'Towels', value: Amenities.TOWELS },
	{ label: 'Bed sheets', value: Amenities.BED_SHEETS },
	{ label: 'Soap', value: Amenities.SOAP },
	{ label: 'Toilet paper', value: Amenities.TOILET_PAPER },
	{ label: 'Hot water', value: Amenities.HOT_WATER },
	{ label: 'Hangers', value: Amenities.HANGERS },
	{ label: 'Stove', value: Amenities.STOVE },
	{ label: 'Oven', value: Amenities.OVEN },
	{ label: 'Refrigerator', value: Amenities.REFRIGERATOR },
	{ label: 'Microwave', value: Amenities.MICROWAVE },
	{ label: 'Coffee maker', value: Amenities.COFFEE_MAKER },
	{ label: 'Kettle', value: Amenities.KETTLE },
	{ label: 'Cooking basics', value: Amenities.COOKING_BASICS },
	{ label: 'Dishes and cutlery', value: Amenities.DISHES_AND_CUTLERY },
	{ label: 'Dishwasher', value: Amenities.DISHWASHER },
	{ label: 'Washer', value: Amenities.WASHER },
	{ label: 'Dryer', value: Amenities.DRYER },
	{ label: 'Iron', value: Amenities.IRON },
	{ label: 'Ironing board', value: Amenities.IRONING_BOARD },
	{ label: 'Extra pillows', value: Amenities.EXTRA_PILLOWS },
	{ label: 'Blankets', value: Amenities.BLANKETS },
	{ label: 'Blackout curtains', value: Amenities.BLACKOUT_CURTAINS },
	{ label: 'Hair dryer', value: Amenities.HAIR_DRYER },
	{ label: 'Shampoo', value: Amenities.SHAMPOO },
	{ label: 'Conditioner', value: Amenities.CONDITIONER },
	{ label: 'Body soap', value: Amenities.BODY_SOAP },
	{ label: 'Bathtub', value: Amenities.BATHTUB },
	{ label: 'Shower', value: Amenities.SHOWER },
	{ label: 'TV', value: Amenities.TV },
	{ label: 'Streaming services', value: Amenities.STREAMING_SERVICES },
	{ label: 'Sound system', value: Amenities.SOUND_SYSTEM },
	{ label: 'Books', value: Amenities.BOOKS },
	{ label: 'Board games', value: Amenities.BOARD_GAMES },
	{ label: 'Free parking (dedicated)', value: Amenities.FREE_PARKING },
	{ label: 'Paid parking', value: Amenities.PAID_PARKING },
	{ label: 'Elevator', value: Amenities.ELEVATOR },
	{ label: 'Hot tub', value: Amenities.HOT_TUB },
	{ label: 'Gym', value: Amenities.GYM },
	{ label: 'Balcony', value: Amenities.BALCONY },
	{ label: 'Patio', value: Amenities.PATIO },
	{ label: 'Garden', value: Amenities.GARDEN },
	{ label: 'Backyard', value: Amenities.BACKYARD },
	{ label: 'BBQ grill', value: Amenities.BBQ_GRILL },
	{ label: 'Outdoor furniture', value: Amenities.OUTDOOR_FURNITURE },
	{ label: 'Crib', value: Amenities.CRIB },
	{ label: 'High chair', value: Amenities.HIGH_CHAIR },
	{ label: 'Baby bath', value: Amenities.BABY_BATH },
	{ label: 'Children toys', value: Amenities.CHILDREN_TOYS },
	{ label: 'Pets allowed', value: Amenities.PETS_ALLOWED },
	{ label: 'Pet bed', value: Amenities.PET_BED },
	{ label: 'Pet bowls', value: Amenities.PET_BOWLS },
	{ label: 'Smoke alarm', value: Amenities.SMOKE_ALARM },
	{ label: 'Carbon monoxide alarm', value: Amenities.CARBON_MONOXIDE_ALARM },
	{ label: 'First aid kit', value: Amenities.FIRST_AID_KIT },
	{ label: 'Fire extinguisher', value: Amenities.FIRE_EXTINGUISHER },
	{ label: 'Dedicated workspace (full)', value: Amenities.DEDICATED_WORKSPACE },
	{ label: 'Desk', value: Amenities.DESK },
	{ label: 'Chair', value: Amenities.CHAIR },
	{ label: 'Sea view', value: Amenities.SEA_VIEW },
	{ label: 'Mountain view', value: Amenities.MOUNTAIN_VIEW },
	{ label: 'Fireplace', value: Amenities.FIREPLACE },
	{ label: 'Jacuzzi', value: Amenities.JACUZZI },
	{ label: 'Smart lock', value: Amenities.SMART_LOCK },
	{ label: 'Smart home features', value: Amenities.SMART_HOME_FEATURES },
	{ label: 'Outdoor dining area', value: Amenities.OUTDOOR_DINING_AREA },
	{ label: 'Fire pit', value: Amenities.FIRE_PIT },
	{ label: 'Pool table', value: Amenities.POOL_TABLE },
	{ label: 'Indoor fireplace', value: Amenities.INDOOR_FIREPLACE },
	{ label: 'Piano', value: Amenities.PIANO },
	{ label: 'Exercise equipment', value: Amenities.EXERCISE_EQUIPMENT },
	{ label: 'Lake access', value: Amenities.LAKE_ACCESS },
	{ label: 'Beach access', value: Amenities.BEACH_ACCESS },
	{ label: 'Ski-in/Ski-out', value: Amenities.SKI_IN_SKI_OUT },
	{ label: 'Outdoor shower', value: Amenities.OUTDOOR_SHOWER },
] as const;

const amenityIconByValue: Record<AmenityId, LucideIcon> = {
	[Amenities.WIFI]: Wifi,
	[Amenities.POOL]: WavesLadder,
	[Amenities.PARKING]: SquareParking,
	[Amenities.FREE_PARKING]: SquareParking,
	[Amenities.PAID_PARKING]: SquareParking,
	[Amenities.AC]: AirVent,
	[Amenities.AIR_CONDITIONING]: AirVent,
	[Amenities.HEATING]: Heater,
	[Amenities.HOT_WATER]: AirVent,
	[Amenities.KITCHEN]: CookingPot,
	[Amenities.STOVE]: CookingPot,
	[Amenities.OVEN]: CookingPot,
	[Amenities.REFRIGERATOR]: Refrigerator,
	[Amenities.MICROWAVE]: Microwave,
	[Amenities.COFFEE_MAKER]: Coffee,
	[Amenities.KETTLE]: CookingPot,
	[Amenities.COOKING_BASICS]: CookingPot,
	[Amenities.DISHES_AND_CUTLERY]: CookingPot,
	[Amenities.DISHWASHER]: CookingPot,
	[Amenities.BBQ_GRILL]: CookingPot,
	[Amenities.WORKSPACE]: Pickaxe,
	[Amenities.DEDICATED_WORKSPACE]: Pickaxe,
	[Amenities.DESK]: Pickaxe,
	[Amenities.CHAIR]: Pickaxe,
	[Amenities.WASHER]: AirVent,
	[Amenities.DRYER]: AirVent,
	[Amenities.IRON]: AirVent,
	[Amenities.IRONING_BOARD]: AirVent,
	[Amenities.TOWELS]: TowelRack,
	[Amenities.BED_SHEETS]: Bed,
	[Amenities.EXTRA_PILLOWS]: AirVent,
	[Amenities.BLANKETS]: AirVent,
	[Amenities.BLACKOUT_CURTAINS]: AirVent,
	[Amenities.SOAP]: SoapDispenserDroplet,
	[Amenities.TOILET_PAPER]: AirVent,
	[Amenities.HANGERS]: AirVent,
	[Amenities.HAIR_DRYER]: AirVent,
	[Amenities.SHAMPOO]: AirVent,
	[Amenities.CONDITIONER]: AirVent,
	[Amenities.BODY_SOAP]: AirVent,
	[Amenities.BATHTUB]: Waves,
	[Amenities.SHOWER]: Waves,
	[Amenities.TV]: Wifi,
	[Amenities.STREAMING_SERVICES]: Wifi,
	[Amenities.SOUND_SYSTEM]: Wifi,
	[Amenities.BOOKS]: Pickaxe,
	[Amenities.BOARD_GAMES]: Pickaxe,
	[Amenities.ELEVATOR]: AirVent,
	[Amenities.HOT_TUB]: Waves,
	[Amenities.GYM]: Dumbbell,
	[Amenities.BALCONY]: Waves,
	[Amenities.PATIO]: Waves,
	[Amenities.GARDEN]: Waves,
	[Amenities.BACKYARD]: Waves,
	[Amenities.OUTDOOR_FURNITURE]: Waves,
	[Amenities.CRIB]: AirVent,
	[Amenities.HIGH_CHAIR]: AirVent,
	[Amenities.BABY_BATH]: Waves,
	[Amenities.CHILDREN_TOYS]: Pickaxe,
	[Amenities.PETS_ALLOWED]: PawPrint ,
	[Amenities.PET_BED]: AirVent,
	[Amenities.PET_BOWLS]: CookingPot,
	[Amenities.SMOKE_ALARM]: Siren,
	[Amenities.CARBON_MONOXIDE_ALARM]: AirVent,
	[Amenities.FIRST_AID_KIT]: AirVent,
	[Amenities.FIRE_EXTINGUISHER]: AirVent,
	[Amenities.SEA_VIEW]: Waves,
	[Amenities.MOUNTAIN_VIEW]: Mountain,
	[Amenities.FIREPLACE]: AirVent,
	[Amenities.JACUZZI]: Waves,
	[Amenities.SMART_LOCK]: Wifi,
	[Amenities.SMART_HOME_FEATURES]: Wifi,
	[Amenities.OUTDOOR_DINING_AREA]: UtensilsCrossed,
	[Amenities.FIRE_PIT]: Flame,
	[Amenities.POOL_TABLE]: LayoutGrid,
	[Amenities.INDOOR_FIREPLACE]: Flame,
	[Amenities.PIANO]: Music,
	[Amenities.EXERCISE_EQUIPMENT]: Dumbbell,
	[Amenities.LAKE_ACCESS]: Waves,
	[Amenities.BEACH_ACCESS]: TreePalm,
	[Amenities.SKI_IN_SKI_OUT]: Mountain,
	[Amenities.OUTDOOR_SHOWER]: Droplets,
};

export const AmenitiesOptions: AmenityOption[] = amenitiesBaseOptions.map((option) => ({
	...option,
	icon: amenityIconByValue[option.value],
}));

export const amenityOptionByValue = Object.fromEntries(
	AmenitiesOptions.map((o) => [o.value, o]),
) as Record<AmenityId, AmenityOption>;

export const AmenitiesOptionsLabels: Record<AmenityId, string> = {
	[Amenities.WIFI]: 'Wifi',
	[Amenities.POOL]: 'Pool',
	[Amenities.PARKING]: 'Free parking',
	[Amenities.AC]: 'Air conditioning (AC)',
	[Amenities.KITCHEN]: 'Kitchen',
	[Amenities.WORKSPACE]: 'Dedicated workspace',
	[Amenities.HEATING]: 'Heating',
	[Amenities.AIR_CONDITIONING]: 'Air conditioning',
	[Amenities.TOWELS]: 'Towels',
	[Amenities.BED_SHEETS]: 'Bed sheets',
	[Amenities.SOAP]: 'Soap',
	[Amenities.TOILET_PAPER]: 'Toilet paper',
	[Amenities.HOT_WATER]: 'Hot water',
	[Amenities.HANGERS]: 'Hangers',
	[Amenities.STOVE]: 'Stove',
	[Amenities.OVEN]: 'Oven',
	[Amenities.REFRIGERATOR]: 'Refrigerator',
	[Amenities.MICROWAVE]: 'Microwave',
	[Amenities.COFFEE_MAKER]: 'Coffee maker',
	[Amenities.KETTLE]: 'Kettle',
	[Amenities.COOKING_BASICS]: 'Cooking basics',
	[Amenities.DISHES_AND_CUTLERY]: 'Dishes and cutlery',
	[Amenities.DISHWASHER]: 'Dishwasher',
	[Amenities.WASHER]: 'Washer',
	[Amenities.DRYER]: 'Dryer',
	[Amenities.IRON]: 'Iron',
	[Amenities.IRONING_BOARD]: 'Ironing board',
	[Amenities.EXTRA_PILLOWS]: 'Extra pillows',
	[Amenities.BLANKETS]: 'Blankets',
	[Amenities.BLACKOUT_CURTAINS]: 'Blackout curtains',
	[Amenities.HAIR_DRYER]: 'Hair dryer',
	[Amenities.SHAMPOO]: 'Shampoo',
	[Amenities.CONDITIONER]: 'Conditioner',
	[Amenities.BODY_SOAP]: 'Body soap',
	[Amenities.BATHTUB]: 'Bathtub',
	[Amenities.SHOWER]: 'Shower',
	[Amenities.TV]: 'TV',
	[Amenities.STREAMING_SERVICES]: 'Streaming services',
	[Amenities.SOUND_SYSTEM]: 'Sound system',
	[Amenities.BOOKS]: 'Books',
	[Amenities.BOARD_GAMES]: 'Board games',
	[Amenities.FREE_PARKING]: 'Free parking on premises',
	[Amenities.PAID_PARKING]: 'Paid parking on premises',
	[Amenities.ELEVATOR]: 'Elevator',
	[Amenities.HOT_TUB]: 'Hot tub',
	[Amenities.GYM]: 'Gym',
	[Amenities.BALCONY]: 'Balcony',
	[Amenities.PATIO]: 'Patio',
	[Amenities.GARDEN]: 'Garden',
	[Amenities.BACKYARD]: 'Backyard',
	[Amenities.BBQ_GRILL]: 'BBQ grill',
	[Amenities.OUTDOOR_FURNITURE]: 'Outdoor furniture',
	[Amenities.CRIB]: 'Crib',
	[Amenities.HIGH_CHAIR]: 'High chair',
	[Amenities.BABY_BATH]: 'Baby bath',
	[Amenities.CHILDREN_TOYS]: 'Children toys',
	[Amenities.PETS_ALLOWED]: 'Pets allowed',
	[Amenities.PET_BED]: 'Pet bed',
	[Amenities.PET_BOWLS]: 'Pet bowls',
	[Amenities.SMOKE_ALARM]: 'Smoke alarm',
	[Amenities.CARBON_MONOXIDE_ALARM]: 'Carbon monoxide alarm',
	[Amenities.FIRST_AID_KIT]: 'First aid kit',
	[Amenities.FIRE_EXTINGUISHER]: 'Fire extinguisher',
	[Amenities.DEDICATED_WORKSPACE]: 'Dedicated workspace',
	[Amenities.DESK]: 'Desk',
	[Amenities.CHAIR]: 'Chair',
	[Amenities.SEA_VIEW]: 'Sea view',
	[Amenities.MOUNTAIN_VIEW]: 'Mountain view',
	[Amenities.FIREPLACE]: 'Fireplace',
	[Amenities.JACUZZI]: 'Jacuzzi',
	[Amenities.SMART_LOCK]: 'Smart lock',
	[Amenities.SMART_HOME_FEATURES]: 'Smart home features',
	[Amenities.OUTDOOR_DINING_AREA]: 'Outdoor dining area',
	[Amenities.FIRE_PIT]: 'Fire pit',
	[Amenities.POOL_TABLE]: 'Pool table',
	[Amenities.INDOOR_FIREPLACE]: 'Indoor fireplace',
	[Amenities.PIANO]: 'Piano',
	[Amenities.EXERCISE_EQUIPMENT]: 'Exercise equipment',
	[Amenities.LAKE_ACCESS]: 'Lake access',
	[Amenities.BEACH_ACCESS]: 'Beach access',
	[Amenities.SKI_IN_SKI_OUT]: 'Ski-in/Ski-out',
	[Amenities.OUTDOOR_SHOWER]: 'Outdoor shower',
};

/** Grouped list for the property form (subset of all amenity ids). */
export const PROPERTY_FORM_AMENITY_CATEGORIES: {
	id: string;
	title: string;
	description?: string;
	values: AmenityId[];
}[] = [
	{
		id: 'essentials',
		title: 'Essentials',
		values: [
			Amenities.WIFI,
			Amenities.TV,
			Amenities.KITCHEN,
			Amenities.WASHER,
			Amenities.FREE_PARKING,
			Amenities.PAID_PARKING,
			Amenities.AIR_CONDITIONING,
			Amenities.DEDICATED_WORKSPACE,
		],
	},
	{
		id: 'standout',
		title: 'Standout',
		description: 'Do you have any standout amenities?',
		values: [
			Amenities.POOL,
			Amenities.HOT_TUB,
			Amenities.PATIO,
			Amenities.BBQ_GRILL,
			Amenities.OUTDOOR_DINING_AREA,
			Amenities.FIRE_PIT,
			Amenities.POOL_TABLE,
			Amenities.INDOOR_FIREPLACE,
			Amenities.PIANO,
			Amenities.EXERCISE_EQUIPMENT,
			Amenities.LAKE_ACCESS,
			Amenities.BEACH_ACCESS,
			Amenities.SKI_IN_SKI_OUT,
			Amenities.OUTDOOR_SHOWER,
		],
	},
	{
		id: 'safety',
		title: 'Safety',
		description: 'Do you have any of these safety items?',
		values: [
			Amenities.SMOKE_ALARM,
			Amenities.FIRST_AID_KIT,
			Amenities.FIRE_EXTINGUISHER,
			Amenities.CARBON_MONOXIDE_ALARM,
		],
	},
];

export function searchAmenitiesOptions(search: string) {
	const normalizedSearch = search.trim().toLowerCase();
	if (!normalizedSearch) return AmenitiesOptions;

	return AmenitiesOptions.filter((option) => option.label.toLowerCase().includes(normalizedSearch));
}

export function getStaticAmenities(): Array<{ id: string; label: string; icon: LucideIcon }> {
	return AmenitiesOptions.map((option) => ({
		id: option.value,
		label: option.label,
		icon: option.icon,
	}));
}
