export const ApartmentTypes = {
	HOUSE: 'house',
	APARTMENT: 'apartment',
	BARN: 'barn',
	BOAT: 'boat',
	CABIN: 'cabin',
	CAMPER_RV: 'camper_rv',
	CASA_PARTICULAR: 'casa_particular',
	CASTLE: 'castle',
	CAVE: 'cave',
	CONTAINER: 'container',
	CYCLADIC_HOME: 'cycladic_home',
	DAMMUSO: 'dammuso',
	DOME: 'dome',
	EARTH_HOME: 'earth_home',
	FARM: 'farm',
	GUESTHOUSE: 'guesthouse',
	HOTEL: 'hotel',
	HOUSEBOAT: 'houseboat',
	MINSU: 'minsu',
	RIAD: 'riad',
	RYOKAN: 'ryokan',
	SHEPHERDS_HUT: 'shepherds_hut',
	TENT: 'tent',
	TINY_HOME: 'tiny_home',
	TOWER: 'tower',
	TREEHOUSE: 'treehouse',
	TRULLO: 'trullo',
	WINDMILL: 'windmill',
	YURT: 'yurt',
} as const;

export const ApartmentOptions = [
	{ label: 'House', value: ApartmentTypes.HOUSE },
	{ label: 'Apartment', value: ApartmentTypes.APARTMENT },
	{ label: 'Barn', value: ApartmentTypes.BARN },
	{ label: 'Boat', value: ApartmentTypes.BOAT },
	{ label: 'Cabin', value: ApartmentTypes.CABIN },
	{ label: 'Camper/RV', value: ApartmentTypes.CAMPER_RV },
	{ label: 'Casa particular', value: ApartmentTypes.CASA_PARTICULAR },
	{ label: 'Castle', value: ApartmentTypes.CASTLE },
	{ label: 'Cave', value: ApartmentTypes.CAVE },
	{ label: 'Container', value: ApartmentTypes.CONTAINER },
	{ label: 'Cycladic home', value: ApartmentTypes.CYCLADIC_HOME },
	{ label: 'Dammuso', value: ApartmentTypes.DAMMUSO },
	{ label: 'Dome', value: ApartmentTypes.DOME },
	{ label: 'Earth home', value: ApartmentTypes.EARTH_HOME },
	{ label: 'Farm', value: ApartmentTypes.FARM },
	{ label: 'Guesthouse', value: ApartmentTypes.GUESTHOUSE },
	{ label: 'Hotel', value: ApartmentTypes.HOTEL },
	{ label: 'Houseboat', value: ApartmentTypes.HOUSEBOAT },
	{ label: 'Minsu', value: ApartmentTypes.MINSU },
	{ label: 'Riad', value: ApartmentTypes.RIAD },
	{ label: 'Ryokan', value: ApartmentTypes.RYOKAN },
	{ label: "Shepherd's hut", value: ApartmentTypes.SHEPHERDS_HUT },
	{ label: 'Tent', value: ApartmentTypes.TENT },
	{ label: 'Tiny home', value: ApartmentTypes.TINY_HOME },
	{ label: 'Tower', value: ApartmentTypes.TOWER },
	{ label: 'Treehouse', value: ApartmentTypes.TREEHOUSE },
	{ label: 'Trullo', value: ApartmentTypes.TRULLO },
	{ label: 'Windmill', value: ApartmentTypes.WINDMILL },
	{ label: 'Yurt', value: ApartmentTypes.YURT },
] as const;

export const ApartmentOptionsLabels: Record<typeof ApartmentTypes[keyof typeof ApartmentTypes], string> = {
	[ApartmentTypes.HOUSE]: 'House',
	[ApartmentTypes.APARTMENT]: 'Apartment',
	[ApartmentTypes.BARN]: 'Barn',
	[ApartmentTypes.BOAT]: 'Boat',
	[ApartmentTypes.CABIN]: 'Cabin',
	[ApartmentTypes.CAMPER_RV]: 'Camper/RV',
	[ApartmentTypes.CASA_PARTICULAR]: 'Casa particular',
	[ApartmentTypes.CASTLE]: 'Castle',
	[ApartmentTypes.CAVE]: 'Cave',
	[ApartmentTypes.CONTAINER]: 'Container',
	[ApartmentTypes.CYCLADIC_HOME]: 'Cycladic home',
	[ApartmentTypes.DAMMUSO]: 'Dammuso',
	[ApartmentTypes.DOME]: 'Dome',
	[ApartmentTypes.EARTH_HOME]: 'Earth home',
	[ApartmentTypes.FARM]: 'Farm',
	[ApartmentTypes.GUESTHOUSE]: 'Guesthouse',
	[ApartmentTypes.HOTEL]: 'Hotel',
	[ApartmentTypes.HOUSEBOAT]: 'Houseboat',
	[ApartmentTypes.MINSU]: 'Minsu',
	[ApartmentTypes.RIAD]: 'Riad',
	[ApartmentTypes.RYOKAN]: 'Ryokan',
	[ApartmentTypes.SHEPHERDS_HUT]: "Shepherd's hut",
	[ApartmentTypes.TENT]: 'Tent',
	[ApartmentTypes.TINY_HOME]: 'Tiny home',
	[ApartmentTypes.TOWER]: 'Tower',
	[ApartmentTypes.TREEHOUSE]: 'Treehouse',
	[ApartmentTypes.TRULLO]: 'Trullo',
	[ApartmentTypes.WINDMILL]: 'Windmill',
	[ApartmentTypes.YURT]: 'Yurt',
} as const;