
const NEXT_PUBLIC_API_URL = "http://localhost:3000"
const DATABASE_URL = "postgresql://postgres:2702@127.0.0.1:5432/domus"
const CLOUDINARY_CLOUD_NAME = "dgaq7ouhr"
const CLOUDINARY_API_KEY = "651971677934943"
const CLOUDINARY_API_SECRET = "GkWCC-0jbwILVbYmWs11rf1jUy8"
const JWT_SECRET = "2001"
const NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = "AIzaSyBk64CNkm6_abZRdpydwT_tAUGGFHM1wbs"


export const environments = {
NEXT_PUBLIC_API_URL,
DATABASE_URL,
CLOUDINARY_CLOUD_NAME,
CLOUDINARY_API_KEY,
CLOUDINARY_API_SECRET,
JWT_SECRET,
NEXT_PUBLIC_GOOGLE_MAPS_API_KEY,
};
