import '../load-env';

const NEXT_PUBLIC_API_URL = process.env.NEXT_PUBLIC_API_URL
const DATABASE_URL = process.env.DATABASE_URL
const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET
const JWT_SECRET = process.env.JWT_SECRET
const NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY

export const environments = {
NEXT_PUBLIC_API_URL,
DATABASE_URL,
CLOUDINARY_CLOUD_NAME,
CLOUDINARY_API_KEY,
CLOUDINARY_API_SECRET,
JWT_SECRET,
NEXT_PUBLIC_GOOGLE_MAPS_API_KEY,
};
